#!/usr/bin/env python3
"""Build the deterministic, runtime-only Chrome extension archive."""

from base64 import b64encode
from hashlib import sha256
from io import BytesIO
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "generated" / "extensionArchive.ts"
RUNTIME_FILES = (
    "manifest.json",
    "popup.html",
    "popup.css",
    "popup.js",
    "lib/extract.js",
)


def main() -> None:
    buffer = BytesIO()
    with ZipFile(buffer, "w", compression=ZIP_DEFLATED, compresslevel=9) as archive:
        for relative_path in RUNTIME_FILES:
            source = ROOT / "extension" / relative_path
            info = ZipInfo(relative_path, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, source.read_bytes())

    contents = buffer.getvalue()
    digest = sha256(contents).hexdigest()
    encoded = b64encode(contents).decode("ascii")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "// Generated by scripts/package-extension.py. Do not edit.\n"
        f'export const EXTENSION_ARCHIVE_SHA256 = "{digest}";\n'
        f'export const EXTENSION_ARCHIVE_BASE64 = "{encoded}";\n',
        encoding="utf-8",
    )
    print(f"{digest}  add-to-bookie.zip ({len(contents)} bytes)")


if __name__ == "__main__":
    main()
